# Bing ChatGPT wrote this, seems to work.
- name: Install python3, python3-pip, lz4 pip module, p7zip-full, unzip and unp
  hosts: localhost # same way as retronas
  tasks:
    - name: Install python3, python3-pip, p7zip-full, unzip and unp
      apt:
        name:
          - python3
          - python3-pip
          - p7zip-full
          - unzip
          - unp
        state: present
      become: true # sudo / elevation

    - name: Install lz4 pip module
      pip:
        name: lz4
        executable: pip3
# ---------------------------------------------------------
    - name: Download WIT (Wiimms ISO Tools) tarball
      get_url:
        url: https://wit.wiimm.de/download/wit-v3.05a-r8638-x86_64.tar.gz
        dest: /tmp/wit-v3.05a-r8638-x86_64.tar.gz

    - name: Extract WIT tarball
      unarchive:
        src: /tmp/wit-v3.05a-r8638-x86_64.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Install WIT - Migth be slower than the previous steps, it's OK
      command: 'bash ./install.sh'
      args:
        chdir: /tmp/wit-v3.05a-r8638-x86_64   # Necesario al parecer
      become: true
# ---------------------------------------------------------
    - name: Download Wii Script
      get_url:
        url: https://raw.githubusercontent.com/Linx-ESP/auto-compress-roms/main/bash-scripts/wii-iso2wbfs.sh
        dest: /media/games/scripts/wii-iso2wbfs.sh
    - name: Download PS2/OPL Script
      get_url:
        url: https://raw.githubusercontent.com/Linx-ESP/auto-compress-roms/main/bash-scripts/ps2-opl-iso2zso.sh
        dest: /media/games/scripts/ps2-opl-iso2zso.sh
