# Bing ChatGPT wrote this, will check if it works... some day.
- name: Install python3, python3-pip, lz4 pip module, p7zip-full, unzip and unp
#  hosts: localhost # same way as retronas
  tasks:
    - name: Install python3, python3-pip, p7zip-full, unzip and unp
      apt:
        name:
          - python3
          - python3-pip
          - p7zip-full
          - unzip
          - unp
        state: present
      become: yes # sudo / elevation

    - name: Install lz4 pip module
      pip:
        name: lz4
        executable: pip3
